services:
  silly-demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: silly-demo-app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      DB_ENDPOINT: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: sillydemo
    depends_on:
      - db
    networks:
      - silly-net
    command: ./silly-demo

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - silly-demo
    networks:
      - silly-net
    restart: always

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sillydemo
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
    ports:
      - "5433:5432"
    networks:
      - silly-net
    restart: always

volumes:
  pgdata:

networks:
  silly-net:
    driver: bridge
